name: Generar Graficos Comparativos
on:
  schedule:
    - cron: '30 5 * * *' # Se ejecuta 5:30 AM
  workflow_dispatch: # Botón para ejecutar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas matplotlib seaborn

      - name: Run script
        run: python script-climatica.py  # Nombre exacto de tu archivo

      - name: Save Charts
        run: |
          git config --global user.name 'Graficador-Bot'
          git config --global user.email 'bot@github.com'
          # Esto asegura que guarde todo lo que esté en la carpeta comparativa
          git add comparativa_ciudades/*.png
          git commit -m "Actualizacion de graficos: $(date +'%Y-%m-%d')" || exit 0
          git push
