name: Visualizador Climatico Diario

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  generar-graficos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        
      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib seaborn
          
      - name: Ejecutar script de graficos
        run: python script-climatica.py
        
      - name: Commit y Push de las imagenes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          mkdir -p comparativa_ciudades
          git add comparativa_ciudades/
          git commit -m "Actualizacion diaria de graficos comparativos RGA" || echo "No hay cambios para commitear"
          git push origin main
